// Authentication Constants

// export const AUTH_SIGNUP_URL = "https://58e26xkko8.execute-api.us-east-1.amazonaws.com/Live/signup"
export const AUTH_SIGNUP_URL = "https://api.chekdin.com/api/v1/auth/merchant-signup"
// export const AUTH_SIGNIN_URL = "https://58e26xkko8.execute-api.us-east-1.amazonaws.com/Live/signin"
export const AUTH_SIGNIN_URL = "https://api.chekdin.com/api/v1/auth/merchant-login"
export const AUTH_SIGNUP_CONFIRMATION_URL = "https://58e26xkko8.execute-api.us-east-1.amazonaws.com/Live/signupconfirmation"
export const AUTH_GET_USER_URL = "https://58e26xkko8.execute-api.us-east-1.amazonaws.com/Live/getuser"
// export const AUTH_UPDATE_USER_URL = "https://58e26xkko8.execute-api.us-east-1.amazonaws.com/Live/updateuser";
export const AUTH_UPDATE_USER_URL = "https://api.chekdin.com/api/v1/merchant/update";
export const AUTH_UPDATE_USER_HOURS = "https://wrjl182nhl.execute-api.us-east-1.amazonaws.com/Alpha/updatehours";
export const GET_ITEMS_COUPON_MANAGER_URL = "https://p906wgxwwa.execute-api.us-east-1.amazonaws.com/Live/getcoupon"
// export const ADD_ITEM_COUPON_MANAGER_URL = "https://p906wgxwwa.execute-api.us-east-1.amazonaws.com/Live/postcoupon"
// export const ADD_ITEM_COUPON_MANAGER_URL = "https://api.chekdin.com/api/v1/coupon/add-update"
export const ADD_ITEM_COUPON_MANAGER_URL = "https://api.chekdin.com/api/v1/coupon/add"
// export const DELETE_ITEM_COUPON_MANAGER_URL = "https://p906wgxwwa.execute-api.us-east-1.amazonaws.com/Live/deletecoupon";
export const DELETE_ITEM_COUPON_MANAGER_URL = "https://api.chekdin.com/api/v1/coupon/add-update";
export const STRIPE_CONFIG_URL = "https://o1vzllh1q7.execute-api.us-east-1.amazonaws.com/LIVE/stripe_config";
export const STRIPE_SETUP_URL = "https://o1vzllh1q7.execute-api.us-east-1.amazonaws.com/LIVE/stripe_setup";
export const STRIPE_UPDATE_CUSTOMER_URL = "https://o1vzllh1q7.execute-api.us-east-1.amazonaws.com/LIVE/stripe_update_customer";
export const STRIPE_BASIC_PRICE_ID = "price_1MKoyYBcPAnGhlsX9VopyY7O";
export const STRIPE_MS_PRICE_ID = "price_1MKoyYBcPAnGhlsXzIbz9Nic";
export const STRIPE_PUBLIC_KEY = "pk_test_51M4pvGBcPAnGhlsXhUW4RhGjIPNZanT1yIZzCGVxLFLj3YZyE3cXAynncbix86jGu1It1EljKUre2XeSGdr9UxSx00osnUowvv";
export const GET_PHOTO_KEY_URL = "https://wrjl182nhl.execute-api.us-east-1.amazonaws.com/Alpha/getphotokeys";
export const AUTH_FORGOTPASSWORD_URL = "https://58e26xkko8.execute-api.us-east-1.amazonaws.com/Live/forgotpasswordtoken";
export const AUTH_CONFIRMFORGOTPASSWORD_URL = "https://58e26xkko8.execute-api.us-east-1.amazonaws.com/Live/forgotpasswordconfirm";
export const ACTIVE_ITEM_COUPON_MANAGER_URL = "https://p906wgxwwa.execute-api.us-east-1.amazonaws.com/Live/activecoupon";
export const QR_CODE_COUPON_URL = "https://p906wgxwwa.execute-api.us-east-1.amazonaws.com/Live/getqr";
export const MERCHANT_USER_UPDATE = "https://api.chekdin.com/api/v1/merchant/update-merchant-user";
export const MERCHANT_USER_GET = "https://api.chekdin.com/api/v1/merchant/get";